version: '3'
services:
  db:
    container_name: mean-db
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    restart: always